<?php $title = 'Archive Currency rates';
    $this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<a href="<?= $this->url('currency', ['action' => 'add']) ?>">Add new Rate</a>
</p>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Сurrency rates</h3>
            </div>
            <div class="panel-body">
                <p>
                <?php if ($this->paginator) : ?>
                <table class="table">
                    <tr>
                        <th>Code</th>
                        <th>Rate</th>
                        <th>&nbsp;</th>
                    </tr>
                    <?php foreach ($this->paginator as $rate) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($rate->letter_code) ?></td>
                            <td><?= $this->escapeHtml($rate->exchange_rate) ?></td>
                            <td>
                                <a href="<?= $this->url('currency', ['action' => 'edit', 'letter_code' => $rate->letter_code]) ?>">Edit</a>
                                <a href="<?= $this->url('currency', ['action' => 'delete', 'letter_code' => $rate->letter_code]) ?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <?php endif; ?>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Сurrency charts</h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="<?= $filegraph ?>">
                </p>
            </div>
        </div>
    </div>
</div>