<?php $title = 'Archive Currency rates';
    $this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<a href="<?= $this->url('currency', ['action' => 'add']) ?>">Add new Rate</a>
</p>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Сurrency rates</h3>
            </div>
            <div class="panel-body">
                <p>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Сurrency charts</h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="<?= $filegraph ?>">
                </p>
            </div>
        </div>
    </div>
</div>