<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">ZF Currency Rates</span></h1>

    <p>
        You have successfully installed the
        <a href="https://github.com/avoropay/CurrencyRates" target="_blank">ZF Currency Rates</a>.
        Running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/avoropay/CurrencyRates" target="_blank">Fork ZF Currency Rates on GitHub &raquo;</a></p>
</div>

<div class="row">

    <?php
    echo $this->render('currency_day.phtml');
    ?>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">PrivatBank in offices</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Currency</th>
                        <th>Buy</th>
                        <th>Sale</th>
                    </tr>
                    <?php foreach ($this->privat as $rate) :  ?>
                        <tr>
                            <td><?= $this->escapeHtml($rate->ccy) ?></td>
                            <td><?= $this->escapeHtml($rate->buy) ?></td>
                            <td><?= $this->escapeHtml($rate->sale) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

                <p><a class="btn btn-success pull-right" href="/exchange">More Currency &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">PrivatBank CreditCard</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Currency</th>
                        <th>Buy</th>
                        <th>Sale</th>
                    </tr>
                    <?php foreach ($this->privat1 as $rate) :  ?>
                        <tr>
                            <td><?= $this->escapeHtml($rate->ccy) ?></td>
                            <td><?= $this->escapeHtml($rate->buy) ?></td>
                            <td><?= $this->escapeHtml($rate->sale) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

                <p><a class="btn btn-success pull-right" href="exchange">More Currency &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Сurrency charts</h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="<?= $filegraph ?>">
                </p>
                <p><a class="btn btn-success pull-right" href="/currency">More Currency Charts &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
