<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row">

    <?php
    echo $this->render('currency_day.phtml');
    ?>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Currency</th>
                        <th>Buy</th>
                        <th>Sale</th>
                    </tr>
                    <?php foreach ($this->privat as $rate) :  ?>
                        <tr>
                            <td><?= $this->escapeHtml($rate->ccy) ?></td>
                            <td><?= $this->escapeHtml($rate->buy) ?></td>
                            <td><?= $this->escapeHtml($rate->sale) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>Currency</th>
                        <th>Buy</th>
                        <th>Sale</th>
                    </tr>
                    <?php foreach ($this->privat1 as $rate) :  ?>
                        <tr>
                            <td><?= $this->escapeHtml($rate->ccy) ?></td>
                            <td><?= $this->escapeHtml($rate->buy) ?></td>
                            <td><?= $this->escapeHtml($rate->sale) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                    If you need any help or support while developing with ZF,
                    you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding this release. Alternatively, you may subscribe
                    and post questions to the <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
